export const proxyGrid = {
  baseUrl: "http://google.savedimage.com",
  authHeader: "x-grid-secret",
  highlights: [
    "SERP coverage for Google, Bing, and YouTube",
    "Web-to-Markdown and screenshot capture",
    "Social + commerce lookups (Reddit, X, Instagram, TikTok, Amazon)",
  ],
  searchTypes: [
    { type: "google", input: "keyword", example: "best espresso machine" },
    { type: "bing", input: "keyword", example: "best espresso machine" },
    { type: "youtube", input: "video ID/URL", example: "dQw4w9WgXcQ" },
    {
      type: "youtube_info",
      input: "video ID/URL",
      example: "dQw4w9WgXcQ",
    },
    {
      type: "youtube_serp",
      input: "keyword",
      example: "typescript tutorial",
    },
    { type: "similarweb", input: "domain", example: "github.com" },
    { type: "web2md", input: "URL", example: "https://example.com" },
    { type: "screenshot", input: "URL", example: "https://example.com" },
    { type: "hackernews", input: "top/new/best/ID", example: "top" },
    {
      type: "reddit",
      input: "post URL",
      example: "https://reddit.com/r/...",
    },
    {
      type: "twitter",
      input: "tweet URL",
      example: "https://twitter.com/...",
    },
    { type: "instagram", input: "username", example: "natgeo" },
    { type: "tiktok", input: "username", example: "tiktok" },
    { type: "amazon", input: "ASIN/URL", example: "B0..." },
    { type: "crunchbase", input: "slug", example: "openai" },
  ],
  cacheTtl: [
    { type: "youtube", ttl: "30 days" },
    { type: "youtube_info", ttl: "7 days" },
    { type: "youtube_serp", ttl: "4 hours" },
    { type: "google", ttl: "4 hours" },
    { type: "similarweb", ttl: "7 days" },
    { type: "web2md", ttl: "24 hours" },
    { type: "screenshot", ttl: "1 hour" },
    { type: "reddit", ttl: "15 min" },
  ],
  difficultySpeed: [
    {
      service: "YouTube Transcript",
      layer: "L4",
      speed: "~1.4s",
      cost: "Free",
    },
    { service: "YouTube SERP", layer: "L4", speed: "~0.8s", cost: "Free" },
    { service: "YouTube Info", layer: "L4", speed: "~2.1s", cost: "Free" },
    { service: "General Proxy", layer: "L4", speed: "~1.2s", cost: "Free" },
    { service: "SimilarWeb", layer: "L4", speed: "~6.5s", cost: "Free" },
    { service: "Google SERP", layer: "L7", speed: "~22s", cost: "API" },
    { service: "Google SERP Full", layer: "L6", speed: "~25s", cost: "Resi" },
  ],
} as const;
